language: node_js
node_js: "10"
addons:
  apt:
    packages:
    - libsecret-1-dev
script:
  - git clone https://$GH_TOKEN@github.com/vechain/sync2.git
  - cd sync2
  - npm ci
  - npx quasar build -m pwa
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: sync2/dist/pwa
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
